language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer self-update || true
    - composer install --dev --prefer-dist
    - php -S 127.0.0.1:8888 -t "$TRAVIS_BUILD_DIR/www" > /dev/null &

script:
    - bin/atoum -ulr
    - bin/behat -f progress
